service: aws-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
plugins:
  - serverless-plugin-typescript
  - serverless-plugin-warmup
  - serverless-offline

functions:
  api:
    handler: dist/handlers/rimac.handler
    events:
      - httpApi:
          path: /list
          method: get
      - httpApi:
          path: /create
          method: post
